# Generated by Django 6.0.3 on 2026-06-13 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=100)),
                ('car_number', models.CharField(max_length=20)),
                ('price_per_km', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Assigned', 'Assigned'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='drop',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pickup',
            field=models.CharField(max_length=100),
        ),
    ]
