# Generated by Django 6.0.3 on 2026-06-13 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabapp', '0003_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='car_type',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Hatchback', 'Hatchback')], default='Sedan', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Busy', 'Busy')], default='Available', max_length=20),
        ),
    ]
