# Generated by Django 6.0.3 on 2026-10-03 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabapp', '0005_booking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Assigned', 'Assigned'), ('Reached Destination', 'Reached Destination'), ('Cancelled', 'Cancelled')], default='Pending', max_length=30),
        ),
    ]
